import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Provider } from '@/components/ui/provider';
import Navbar from '@/components/ui/Navbar';
import { Flex } from '@chakra-ui/react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Flex
            dir='column'
            minHeight='100svh'
            bgColor='bg.muted'
            justify='center'
          >
            <Navbar />
            <Flex flex={1} mt={14}>
              {children}
            </Flex>
          </Flex>
        </Provider>
      </body>
    </html>
  );
}
